# Generated by Django 2.2.6 on 2019-11-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_of_points',
            field=models.IntegerField(default=0),
        ),
    ]
