# Generated by Django 2.2.6 on 2019-11-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_total_of_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
