# Generated by Django 2.2.7 on 2019-11-09 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizenopinion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 18, 52, 31, 806079), verbose_name='Дата публикации'),
        ),
    ]
