# Generated by Django 2.2.6 on 2019-11-10 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizenopinion', '0002_auto_20191110_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
