# Generated by Django 2.2.7 on 2019-11-09 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizenopinion', '0002_auto_20191109_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='couner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 19, 0, 18, 674406), verbose_name='Дата публикации'),
        ),
    ]
