# Generated by Django 2.2.7 on 2019-11-09 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizenopinion', '0004_auto_20191109_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 19, 51, 5, 440540), verbose_name='Дата публикации'),
        ),
    ]
