# Generated by Django 2.2.7 on 2019-11-09 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizenopinion', '0006_auto_20191109_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 19, 53, 6, 81198), verbose_name='Дата публикации'),
        ),
    ]
